spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "Existing order database"

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: >-
          orderConfirmation:com.elsebaey.ecommerce.kafka.OrderConfirmation,
          orderStatusUpdate:com.elsebaey.ecommerce.kafka.OrderStatusUpdate

server:
  port: 8070

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    # payment-url: http://localhost:8222/api/v1/payments